version: '3'
services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
     - TZ=Europe/Berlin
    restart: always
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"